import { ToolPageConfig } from "@/lib/tool-pages";

export const portugueseToolConfigs: Record<string, ToolPageConfig> = {
  "webp-converter": {
    path: "/pt/free-webp-converter",
    navLabel: "Conversor WebP",
    metaTitle: "Conversor WebP Grátis Online — Rápido e Sem Limites | ImageSEO",
    metaDescription: "Converta fotos para o formato WebP moderno instantaneamente. Reduza o peso do seu site mantendo excelente qualidade visual com processamento local seguro.",
    h1: "Conversor WebP Grátis Online no Navegador",
    heroEyebrow: "Conversão local no navegador",
    heroBody: "Transforme imagens JPG, PNG, AVIF e outros formatos em WebP diretamente no navegador. Melhore o Core Web Vitals e o tempo de carregamento sem enviar arquivos para servidores.",
    mode: "format-converter",
    defaultTargetFormat: "WEBP",
    accent: "bg-gradient-to-b from-sky-50 via-background to-background dark:from-sky-950/20",
    badgeClass: "border-sky-200 bg-sky-50 text-sky-700 dark:border-sky-800 dark:bg-sky-950/40 dark:text-sky-300",
    primaryKeyword: "conversor webp gratis",
    secondaryKeywords: ["converter imagem para webp", "converter jpg em webp", "converter png em webp"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "Selecione ou arraste suas fotos", body: "Carregue imagens JPG, PNG ou AVIF com total privacidade." },
      { title: "Ajuste a qualidade WebP", body: "Escolha a taxa de compressão ideal entre nitidez e tamanho reduzido." },
      { title: "Baixe instantaneamente", body: "Salve os arquivos WebP individualmente ou em arquivo ZIP compacto." },
    ],
    faqs: [
      { q: "Por que converter imagens para WebP?", a: "O formato WebP gera arquivos até 35% menores que o JPEG com a mesma qualidade visual." },
    ],
  },
  "geo-tagger": {
    path: "/pt/free-geo-tagger",
    navLabel: "Geotag GPS",
    metaTitle: "Adicionar Localização em Fotos Grátis — Editor EXIF GPS | ImageSEO",
    metaDescription: "Insira coordenadas GPS e metadatos EXIF em fotos para impulsionar o SEO local e o Perfil da Empresa no Google. Mapa interativo 100% privado.",
    h1: "Geotag de Fotos e Editor EXIF GPS Grátis",
    heroEyebrow: "Editor EXIF GPS 100% confidencial",
    heroBody: "Insira latitude e longitude em fotos JPEG diretamente no seu navegador. Melhore a relevância local no Google Maps e Google Meu Negócio.",
    mode: "geo-tagger",
    accent: "bg-gradient-to-b from-emerald-50 via-background to-background dark:from-emerald-950/20",
    badgeClass: "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300",
    primaryKeyword: "adicionar localizacao em foto",
    secondaryKeywords: ["geotag foto gratis", "editor exif gps", "colocar localizacao em imagem"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "Encontre seu local no mapa", body: "Digite o endereço ou mova o marcador para capturar as coordenadas exatas." },
      { title: "Carregue as fotografias", body: "Arraste as fotos que deseja marcar geograficamente." },
      { title: "Injete os dados EXIF e baixe", body: "Baixe os arquivos JPEG com as coordenadas GPS embutidas." },
    ],
    faqs: [
      { q: "Como o geotag ajuda no SEO local?", a: "Os metadados GPS confirmam para os motores de busca onde o serviço ou foto foi realizado." },
    ],
  },
  "online-image-compressor": {
    path: "/pt/free-online-image-compressor",
    navLabel: "Compressor de Fotos",
    metaTitle: "Compressor de Imagens Online Grátis — Diminuir Tamanho de Fotos | ImageSEO",
    metaDescription: "Comprima fotos JPG, PNG e WebP em lote mantendo alta qualidade. Ferramenta rápida, segura e sem limites de upload com processamento local no navegador.",
    h1: "Compressor de Imagens Online Grátis e Ilimitado",
    heroEyebrow: "Compressão de imagens no navegador",
    heroBody: "Comprima várias fotos JPG, PNG e WebP de uma só vez sem fila nem perda visual perceptível. 100% no seu dispositivo.",
    mode: "compressor",
    accent: "bg-gradient-to-b from-violet-50 via-background to-background dark:from-violet-950/20",
    badgeClass: "border-violet-200 bg-violet-50 text-violet-700 dark:border-violet-800 dark:bg-violet-950/40 dark:text-violet-300",
    primaryKeyword: "comprimir fotos online",
    secondaryKeywords: ["diminuir tamanho de foto", "reduzir tamanho de imagem", "comprimir jpg"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "Arraste suas imagens", body: "Selecione quantas fotos quiser sem limites de upload." },
      { title: "Ajuste o controle de qualidade", body: "Defina o nível de compressão desejado." },
      { title: "Baixe com um clique", body: "Baixe individualmente ou em arquivo ZIP consolidado." },
    ],
    faqs: [
      { q: "As fotos são enviadas para algum servidor?", a: "Não. Todo o processamento ocorre no próprio navegador via HTML5 Canvas." },
    ],
  },
};

export const arabicToolConfigs: Record<string, ToolPageConfig> = {
  "webp-converter": {
    path: "/ar/free-webp-converter",
    navLabel: "محول WebP",
    metaTitle: "محول صور WebP مجاني أونلاين — بدون قيود حجم | ImageSEO",
    metaDescription: "حول الصور إلى صيغة WebP فائقة الخفة على الفور. سرّع موقعك الإلكتروني مع الحفاظ على دقة وجودة الصورة بمعالجة محلية آمنة داخل متصفحك.",
    h1: "محول صور WebP مجاني وسريع في المتصفح",
    heroEyebrow: "معالجة محلية داخل المتصفح",
    heroBody: "حول صور JPG و PNG و AVIF إلى صيغة WebP الحديثة مباشرة داخل متصفحك لتقليل حجم الصفحات وتسريع تجربة المستخدم دون رفع ملفاتك إلى خوادم خارجية.",
    mode: "format-converter",
    defaultTargetFormat: "WEBP",
    accent: "bg-gradient-to-b from-sky-50 via-background to-background dark:from-sky-950/20",
    badgeClass: "border-sky-200 bg-sky-50 text-sky-700 dark:border-sky-800 dark:bg-sky-950/40 dark:text-sky-300",
    primaryKeyword: "تحويل الصور الى webp",
    secondaryKeywords: ["تحويل jpg الى webp", "تحويل png الى webp", "برنامج تحويل webp"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "اختر أو اسحب الصور", body: "قم برفع الصور بأي صيغة مباشرة دون انتظار." },
      { title: "حدد جودة التحويل", body: "اختر نسبة الضغط والجودة المناسبة لاحتياجاتك." },
      { title: "حمّل الصور فورًا", body: "احفظ الصور بصيغة WebP بشكل فردي أو في ملف ZIP." },
    ],
    faqs: [
      { q: "لماذا يفضل استخدام صيغة WebP؟", a: "توفر صيغة WebP ضغطًا أعلى بنسبة 35% مقارنة بـ JPEG مع الحفاظ الكامل على نقاء الصورة." },
    ],
  },
  "geo-tagger": {
    path: "/ar/free-geo-tagger",
    navLabel: "تحديد موقع GPS",
    metaTitle: "إضافة إحداثيات GPS للصور أونلاين مجانًا — معدل EXIF | ImageSEO",
    metaDescription: "أضف إحداثيات جغرافية وبيانات الموقع لصورك لتعزيز السيو المحلي ونتائج Google Business Profile عبر خريطة تفاعلية آمنة في المتصفح.",
    h1: "إضافة إحداثيات GPS وتعديل بيانات EXIF للصور مجانًا",
    heroEyebrow: "تعديل بيانات EXIF بخصوصية تامة",
    heroBody: "أضف خطوط الطول والعرض للصور لدعم السيو المحلي وتحسين ظهور نشاطك في خرائط جوجل Google Maps.",
    mode: "geo-tagger",
    accent: "bg-gradient-to-b from-emerald-50 via-background to-background dark:from-emerald-950/20",
    badgeClass: "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300",
    primaryKeyword: "إضافة إحداثيات للصورة",
    secondaryKeywords: ["تحديد موقع الصورة gps", "تعديل بيانات exif للصور", "جيو تاج للصور"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "حدد الموقع على الخريطة", body: "ابحث عن العنوان أو حرك المؤشر للحصول على الإحداثيات الدقيقة." },
      { title: "ارفع الصور", body: "اسحب صور أعمالك أو منتجاتك المراد تحديد موقعها." },
      { title: "احفظ وحمّل الصور", body: "حمّل الصور الجاهزة المدمج بها بيانات الموقع الجغرافي." },
    ],
    faqs: [
      { q: "كيف يساعد Geotagging في السيو المحلي؟", a: "تمنح بيانات GPS محركات البحث دليلاً جغرافيًا موثوقًا على موقع التقاط الصور ونشاطك التجاري." },
    ],
  },
  "online-image-compressor": {
    path: "/ar/free-online-image-compressor",
    navLabel: "ضغط الصور",
    metaTitle: "ضغط الصور أونلاين مجانًا — تقليل حجم الصور بدون فقدان الجودة | ImageSEO",
    metaDescription: "اضغط صور JPG و PNG و WebP دفعة واحدة مع الاحتفاظ بأعلى جودة بصرية. معالجة سريعة وآمنة 100% داخل المتصفح دون حفظ أي بيانات.",
    h1: "برنامج ضغط الصور أونلاين مجانًا وبلا حدود",
    heroEyebrow: "ضغط الصور محليًا في المتصفح",
    heroBody: "قلل حجم ملفات الصور بالكيلوبايت دفعة واحدة مع الحفاظ على وضوح التفاصيل دون قيود أو إعلانات مزعجة.",
    mode: "compressor",
    accent: "bg-gradient-to-b from-violet-50 via-background to-background dark:from-violet-950/20",
    badgeClass: "border-violet-200 bg-violet-50 text-violet-700 dark:border-violet-800 dark:bg-violet-950/40 dark:text-violet-300",
    primaryKeyword: "ضغط الصور مجانا",
    secondaryKeywords: ["تقليل حجم الصور", "ضغط صور jpg", "تصغير حجم الصور بالكيلوبايت"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "اسحب الصور", body: "اختر أي عدد من الصور دفعة واحدة دون حدود حجم." },
      { title: "تحكم بالجودة", body: "اضبط مؤشر الجودة للوصول إلى أفضل توازن." },
      { title: "حمّل الصور بنقرة واحدة", body: "احفظ الصور فورًا على جهازك بأمان تام." },
    ],
    faqs: [
      { q: "هل تبقى صوري آمنة وخاصة؟", a: "نعم، تتم جميع العمليات داخل جهازك عبر المتصفح دون إرسال أي بايت إلى خوادم خارجية." },
    ],
  },
};

export const indonesianToolConfigs: Record<string, ToolPageConfig> = {
  "webp-converter": {
    path: "/id/free-webp-converter",
    navLabel: "Konverter WebP",
    metaTitle: "Konverter WebP Gratis Online — Ubah Gambar ke WebP | ImageSEO",
    metaDescription: "Ubah gambar menjadi format WebP modern secara instan. Perkacil ukuran file gambar dan percepat loading website toko online atau blog Anda.",
    h1: "Konverter WebP Gratis & Cepat di Browser",
    heroEyebrow: "Konversi gambar lokal di browser",
    heroBody: "Ubah file gambar JPG, PNG, AVIF ke WebP langsung di browser tanpa upload ke server. Tingkatkan Core Web Vitals dan kecepatan website secara instan.",
    mode: "format-converter",
    defaultTargetFormat: "WEBP",
    accent: "bg-gradient-to-b from-sky-50 via-background to-background dark:from-sky-950/20",
    badgeClass: "border-sky-200 bg-sky-50 text-sky-700 dark:border-sky-800 dark:bg-sky-950/40 dark:text-sky-300",
    primaryKeyword: "ubah foto ke webp",
    secondaryKeywords: ["ubah jpg ke webp", "convert jpg ke webp", "konverter webp online"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "Pilih foto", body: "Unggah gambar JPG atau PNG dengan aman di perangkat Anda." },
      { title: "Atur kualitas", body: "Tentukan tingkat kompresi sesuai kebutuhan ketajaman gambar." },
      { title: "Unduh file WebP", body: "Download file WebP secara instan tanpa batas kuota." },
    ],
    faqs: [
      { q: "Mengapa harus menggunakan format WebP?", a: "WebP berukuran hingga 35% lebih kecil dibandingkan JPG dengan kualitas visual yang sama tajamnya." },
    ],
  },
  "geo-tagger": {
    path: "/id/free-geo-tagger",
    navLabel: "Geotag GPS",
    metaTitle: "Tambah Lokasi Foto Online Gratis — Edit EXIF GPS | ImageSEO",
    metaDescription: "Tambahkan koordinat GPS dan lokasi akurat pada foto untuk memperkuat SEO lokal dan profil Google Bisnisku. Menggunakan peta interaktif yang aman di browser.",
    h1: "Geotag Foto & Edit Metadata EXIF GPS Gratis",
    heroEyebrow: "Geotagging foto 100% aman & privat",
    heroBody: "Sematkan koordinat latitude dan longitude pada foto JPEG Anda untuk meningkatkan peringkat di Google Bisnisku (GBP) dan pencarian lokal.",
    mode: "geo-tagger",
    accent: "bg-gradient-to-b from-emerald-50 via-background to-background dark:from-emerald-950/20",
    badgeClass: "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300",
    primaryKeyword: "tambah lokasi foto",
    secondaryKeywords: ["geotag foto online", "edit exif gps foto", "pasang lokasi pada foto"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "Cari lokasi di peta", body: "Tentukan titik koordinat akurat pada peta interaktif." },
      { title: "Pilih foto usaha", body: "Unggah foto proyek, toko, atau produk Anda." },
      { title: "Simpan data GPS", body: "Unduh foto JPEG yang telah disematkan metadata lokasi GPS." },
    ],
    faqs: [
      { q: "Apa manfaat geotag untuk SEO lokal?", a: "Data koordinat GPS membantu Google memvalidasi keberadaan fisik dan lokasi usaha Anda." },
    ],
  },
  "online-image-compressor": {
    path: "/id/free-online-image-compressor",
    navLabel: "Kompres Foto",
    metaTitle: "Kompres Foto Online Gratis — Perkecil Ukuran Foto Cepat | ImageSEO",
    metaDescription: "Kompres banyak foto JPG, PNG, dan WebP sekaligus tanpa mengurangi ketajaman visual. 100% diproses di browser tanpa antrean dan tanpa batas upload.",
    h1: "Kompres Foto Online Gratis & Tanpa Batas",
    heroEyebrow: "Kompresi foto cepat di browser",
    heroBody: "Kecilkan ukuran file foto JPG, PNG, dan WebP secara massal dengan cepat tanpa antrean server dan 100% menjaga privasi foto Anda.",
    mode: "compressor",
    accent: "bg-gradient-to-b from-violet-50 via-background to-background dark:from-violet-950/20",
    badgeClass: "border-violet-200 bg-violet-50 text-violet-700 dark:border-violet-800 dark:bg-violet-950/40 dark:text-violet-300",
    primaryKeyword: "kompres foto online",
    secondaryKeywords: ["perkecil ukuran foto", "kompres jpg", "kurangi ukuran foto kb"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "Pilih banyak foto", body: "Tarik atau pilih foto tanpa batas ukuran file." },
      { title: "Sesuaikan kualitas", body: "Atur slider kompresi untuk ukuran yang pas." },
      { title: "Unduh langsung", body: "Download hasil foto satu per satu atau dalam file ZIP." },
    ],
    faqs: [
      { q: "Apakah foto saya diunggah ke server?", a: "Tidak. Semua pemrosesan berlangsung di browser Anda secara offline/lokal." },
    ],
  },
};

export const hindiToolConfigs: Record<string, ToolPageConfig> = {
  "webp-converter": {
    path: "/hi/free-webp-converter",
    navLabel: "WebP कनवर्टर",
    metaTitle: "WebP कनवर्टर मुफ़्त ऑनलाइन — इमेज को WebP में बदलें | ImageSEO",
    metaDescription: "अपनी तस्वीरों को आधुनिक WebP फॉर्मेट में तुरंत बदलें। बिना क्वालिटी खोए वेबसाइट और ब्लॉग की लोडिंग स्पीड को सुपरफास्ट बनाएं।",
    h1: "फ़ोटो को WebP में बदलने का मुफ़्त कनवर्टर",
    heroEyebrow: "100% सुरक्षित ब्राउज़र कनवर्टर",
    heroBody: "JPG, PNG और अन्य तस्वीरों को Google के आधुनिक WebP फॉर्मेट में बदलें। बिना किसी सर्वर अपलोड के वेबसाइट स्पीड और मोबाइल परफॉर्मेंस बेहतर करें।",
    mode: "format-converter",
    defaultTargetFormat: "WEBP",
    accent: "bg-gradient-to-b from-sky-50 via-background to-background dark:from-sky-950/20",
    badgeClass: "border-sky-200 bg-sky-50 text-sky-700 dark:border-sky-800 dark:bg-sky-950/40 dark:text-sky-300",
    primaryKeyword: "फोटो को webp में बदलें",
    secondaryKeywords: ["jpg से webp कन्वर्टर", "png से webp कन्वर्टर", "इमेज कन्वर्टर ऑनलाइन"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "फ़ोटो चुनें", body: "JPG या PNG तस्वीरों को सुरक्षित रूप से चुनें।" },
      { title: "क्वालिटी सेट करें", body: "अपनी पसंद के अनुसार कम्प्रेशन लेवल चुनें।" },
      { title: "तुरंत डाउनलोड करें", body: "बिना किसी सीमा के WebP फाइलें तुरंत सेव करें।" },
    ],
    faqs: [
      { q: "WebP फॉर्मेट का क्या फ़ायदा है?", a: "WebP फॉर्मेट समान क्वालिटी में JPG से 35% तक हल्का होता है, जिससे वेबसाइट बहुत तेज़ी से खुलती है।" },
    ],
  },
  "geo-tagger": {
    path: "/hi/free-geo-tagger",
    navLabel: "GPS जियोटैगर",
    metaTitle: "फ़ोटो में GPS लोकेशन जोड़ें — मुफ़्त EXIF जियोटैगर | ImageSEO",
    metaDescription: "लोकल एसईओ और Google Business Profile के लिए फ़ोटो में सटीक GPS कोऑर्डिनेट्स और EXIF डेटा जोड़ें। इंटरएक्टिव मैप के साथ 100% सुरक्षित।",
    h1: "फ़ोटो में लोकेशन डालने और EXIF GPS एडिट करने का मुफ़्त टूल",
    heroEyebrow: "प्राइवेट EXIF लोकेशन एडिटर",
    heroBody: "अपनी बिज़नेस और प्रोडक्ट तस्वीरों में सटीक GPS लोकेशन और EXIF कोऑर्डिनेट्स जोड़ें ताकि Google Maps और लोकल सर्च में बेहतर रैंकिंग मिल सके।",
    mode: "geo-tagger",
    accent: "bg-gradient-to-b from-emerald-50 via-background to-background dark:from-emerald-950/20",
    badgeClass: "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300",
    primaryKeyword: "फोटो में लोकेशन डालना",
    secondaryKeywords: ["फोटो का gps लोकेशन कैसे देखें", "इमेज जियोटैगिंग टूल", "फोटो में पता डालना"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "मैप पर लोकेशन चुनें", body: "सटीक लोकेशन खोजने के लिए मैप पर पिन सेट करें।" },
      { title: "फ़ोटो अपलोड करें", body: "जिन तस्वीरों में लोकेशन जोड़नी है उन्हें चुनें।" },
      { title: "GPS डेटा जोड़ें और डाउनलोड करें", body: "लोकेशन टैग की गई JPG फ़ाइल डाउनलोड करें।" },
    ],
    faqs: [
      { q: "जियोटैगिंग से लोकल एसईओ में क्या मदद मिलती है?", a: "GPS डेटा से गूगल को प्रमाणित होता है कि फ़ोटो वास्तव में उसी शहर या दुकान पर खींची गई है।" },
    ],
  },
  "online-image-compressor": {
    path: "/hi/free-online-image-compressor",
    navLabel: "फोटो कम्प्रेसर",
    metaTitle: "फोटो का साइज कम करें — मुफ़्त इमेज कम्प्रेसर ऑनलाइन | ImageSEO",
    metaDescription: "JPG, PNG और WebP तस्वीरों को एक साथ कम्प्रेस करें बिना क्लेरिटी खोए। सरकारी फॉर्म, जॉब पोर्टल और वेबसाइट के लिए तुरंत साइज़ कम करें।",
    h1: "फोटो का साइज कम करने का मुफ़्त ऑनलाइन टूल",
    heroEyebrow: "ब्राउज़र में तेज़ फोटो कम्प्रेशन",
    heroBody: "सरकारी फॉर्म, प्रतियोगी परीक्षाओं और वेबसाइट के लिए कई JPG, PNG तस्वीरों का साइज़ एक साथ KB में कम करें। 100% मुफ़्त और सुरक्षित।",
    mode: "compressor",
    accent: "bg-gradient-to-b from-violet-50 via-background to-background dark:from-violet-950/20",
    badgeClass: "border-violet-200 bg-violet-50 text-violet-700 dark:border-violet-800 dark:bg-violet-950/40 dark:text-violet-300",
    primaryKeyword: "फोटो का साइज कम करना",
    secondaryKeywords: ["फोटो कम्प्रेस", "jpg फोटो कम्प्रेस", "इमेज का साइज कम करना"],
    schemaType: "WebApplication",
    howToSteps: [
      { title: "तस्वीरें चुनें", body: "जितनी चाहें उतनी तस्वीरें बिना लिमिट के चुनें।" },
      { title: "क्वालिटी स्लाइडर सेट करें", body: "ज़रूरत के मुताबिक फ़ाइल साइज़ सेट करें।" },
      { title: "एक क्लिक में डाउनलोड करें", body: "कम्प्रेस की गई तस्वीरें तुरंत डाउनलोड करें।" },
    ],
    faqs: [
      { q: "क्या मेरी तस्वीरें सर्वर पर अपलोड होती हैं?", a: "बिल्कुल नहीं। पूरा प्रोसेस केवल आपके अपने फ़ोन या कंप्यूटर के ब्राउज़र में होता है।" },
    ],
  },
};
